apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-nodeclass
spec:
  # IAM instance profile for the nodes
  instanceProfile: nodekarpenter-role

  # AMI selection using SSM parameter (dynamic, recommended)
  amiSelectorTerms:
    - ssmParameter: "/aws/service/eks/optimized-ami/1.35/amazon-linux-2023/x86_64/standard/recommended/image_id"

  # Subnets Karpenter can launch nodes into
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: cluster

  # Security groups Karpenter nodes should attach to
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: cluster

  # Optional EC2 metadata options
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
    httpPutResponseHopLimit: 1
    httpProtocolIPv6: disabled