apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-nodeclass
spec:
  instanceProfile: nodekarpenter-role

  # AMI selection using SSM
  amiSelectorTerms:
    - ssmParameter: "/aws/service/eks/optimized-ami/1.35/amazon-linux-2023/x86_64/standard/recommended/image_id"

  # Specify amiFamily since we are not using alias
  amiFamily: AL2   # Amazon Linux 2 / AL2023 (AL2 works for AL2023 too)

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: cluster

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: cluster

  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
    httpPutResponseHopLimit: 1
    httpProtocolIPv6: disabled